export const COMPLETE_DATABASE = [
  {
    url: "/alaska-business-list/",
    state: "Alaska",
    directContacts: 136539,
    uniqueCompanies: 77809,
    uniqueTelephoneNumbers: 66865,
    uniqueFaxNumbers: 6714,
    uniqueMailAddress: 57938,
    facebookAccounts: 463,
    twitterAccounts: 312,
    price: 59,
    tollFreeNumbers: 1257,
    uniqueWebsites: 17683,
    uniqueJobTitles: 403,
    numberOfSic2: 87,
    metaTitle: "Alaska Business List 2022 - Alaska Company Database",
    metaDescription:
      "Our Company Provide Fresh Alaska Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Alaska Sample.csv",
  },
  {
    url: "/alabama-business-list/",
    state: "Alabama",
    directContacts: 563795,
    uniqueCompanies: 378902,
    uniqueTelephoneNumbers: 343150,
    uniqueFaxNumbers: 24218,
    uniqueMailAddress: 320951,
    facebookAccounts: 1827,
    twitterAccounts: 1210,
    price: 96,
    tollFreeNumbers: 5113,
    uniqueWebsites: 71148,
    uniqueJobTitles: 511,
    numberOfSic2: 87,
    metaTitle: "Alabama Business List 2022 - Alabama Company Database",
    metaDescription:
      "Our Company Provide Fresh Alabama Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Alabama Sample.csv",
  },
  {
    url: "/arkansas-business-list/",
    state: "Arkansas",
    directContacts: 352011,
    uniqueCompanies: 230120,
    uniqueTelephoneNumbers: 206798,
    uniqueFaxNumbers: 14698,
    uniqueMailAddress: 196172,
    facebookAccounts: 1039,
    twitterAccounts: 679,
    price: 81,
    tollFreeNumbers: 3197,
    uniqueWebsites: 39418,
    uniqueJobTitles: 480,
    numberOfSic2: 86,
    metaTitle: "Arkansas Business List 2022 - Arkansas Company Database",
    metaDescription:
      "Our Company Provide Fresh Arkansas Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Arkansas Sample.csv",
  },
  {
    url: "/arizona-business-list/",
    state: "Arizona",
    directContacts: 871994,
    uniqueCompanies: 535105,
    uniqueTelephoneNumbers: 466205,
    uniqueFaxNumbers: 30407,
    uniqueMailAddress: 431288,
    facebookAccounts: 4633,
    twitterAccounts: 3525,
    price: 134,
    tollFreeNumbers: 4968,
    uniqueWebsites: 113366,
    uniqueJobTitles: 531,
    numberOfSic2: 87,
    metaTitle: "Arizona Business List 2022 - Arizona Company Database",
    metaDescription:
      "Our Company Provide Fresh Arizona Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Arizona Sample.csv",
  },
  {
    url: "/california-business-list/",
    state: "California",
    directContacts: 5806590,
    uniqueCompanies: 3169623,
    uniqueTelephoneNumbers: 2932072,
    uniqueFaxNumbers: 201529,
    uniqueMailAddress: 2576256,
    facebookAccounts: 104514,
    twitterAccounts: 20147,
    price: 261,
    tollFreeNumbers: 29787,
    uniqueWebsites: 648062,
    uniqueJobTitles: 600,
    numberOfSic2: 89,
    metaTitle: "California Business List 2022 - California Company Database",
    metaDescription:
      "Our Company Provide Fresh California Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "California Sample.csv",
  },
  {
    url: "/colorado-business-list/",
    state: "Colorado",
    directContacts: 974080,
    uniqueCompanies: 571977,
    uniqueTelephoneNumbers: 494848,
    uniqueFaxNumbers: 33468,
    uniqueMailAddress: 459626,
    facebookAccounts: 4329,
    twitterAccounts: 3229,
    price: 149,
    tollFreeNumbers: 5944,
    uniqueWebsites: 128046,
    uniqueJobTitles: 536,
    numberOfSic2: 88,
    metaTitle: "Colorado Business List 2022 - Colorado Company Database",
    metaDescription:
      "Our Company Provide Fresh Colorado Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Colorado Sample.csv",
  },
  {
    url: "/connecticut-business-list/",
    state: "Connecticut",
    directContacts: 763044,
    uniqueCompanies: 378123,
    uniqueTelephoneNumbers: 319123,
    uniqueFaxNumbers: 24292,
    uniqueMailAddress: 266793,
    facebookAccounts: 2358,
    twitterAccounts: 1750,
    price: 134,
    tollFreeNumbers: 4489,
    uniqueWebsites: 83270,
    uniqueJobTitles: 527,
    numberOfSic2: 88,
    metaTitle: "Connecticut Business List 2022 - Connecticut Company Database",
    metaDescription:
      "Our Company Provide Fresh Connecticut Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Connecticut Sample.csv",
  },
  {
    url: "/washington-d-c-business-list/",
    state: "Washington, D.C.",
    directContacts: 537124,
    uniqueCompanies: 118652,
    uniqueTelephoneNumbers: 86778,
    uniqueFaxNumbers: 7341,
    uniqueMailAddress: 67715,
    facebookAccounts: 533,
    twitterAccounts: 495,
    price: 134,
    tollFreeNumbers: 809,
    uniqueWebsites: 28505,
    uniqueJobTitles: 512,
    numberOfSic2: 87,
    metaTitle:
      "Washington, D.C. Business List 2022 - Washington, D.C. Company Database",
    metaDescription:
      "Our Company Provide Fresh Washington, D.C. Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Washington, D.C. Sample.csv",
  },
  {
    url: "/delaware-business-list/",
    state: "Delaware",
    directContacts: 134632,
    uniqueCompanies: 87087,
    uniqueTelephoneNumbers: 73679,
    uniqueFaxNumbers: 4817,
    uniqueMailAddress: 65884,
    facebookAccounts: 674,
    twitterAccounts: 544,
    price: 59,
    tollFreeNumbers: 1032,
    uniqueWebsites: 18873,
    uniqueJobTitles: 430,
    numberOfSic2: 85,
    metaTitle: "Delaware Business List 2022 - Delaware Company Database",
    metaDescription:
      "Our Company Provide Fresh Delaware Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Delaware Sample.csv",
  },
  {
    url: "/florida-business-list/",
    state: "Florida",
    directContacts: 3177096,
    uniqueCompanies: 2144274,
    uniqueTelephoneNumbers: 1898278,
    uniqueFaxNumbers: 101337,
    uniqueMailAddress: 1769125,
    facebookAccounts: 170517,
    twitterAccounts: 16980,
    price: 231,
    tollFreeNumbers: 17414,
    uniqueWebsites: 270098,
    uniqueJobTitles: 583,
    numberOfSic2: 89,
    metaTitle: "Florida Business List 2022 - Florida Company Database",
    metaDescription:
      "Our Company Provide Fresh Florida Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Florida Sample.csv",
  },
  {
    url: "/georgia-business-list/",
    state: "Georgia",
    directContacts: 855640,
    uniqueCompanies: 597353,
    uniqueTelephoneNumbers: 575357,
    uniqueFaxNumbers: 36650,
    uniqueMailAddress: 531678,
    facebookAccounts: 4440,
    twitterAccounts: 3688,
    price: 134,
    tollFreeNumbers: 7287,
    uniqueWebsites: 111552,
    uniqueJobTitles: 520,
    numberOfSic2: 89,
    metaTitle: "Georgia Business List 2022 - Georgia Company Database",
    metaDescription:
      "Our Company Provide Fresh Georgia Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Georgia Sample.csv",
  },
  {
    url: "/guam-business-list/",
    state: "Guam",
    directContacts: 651,
    uniqueCompanies: 285,
    uniqueTelephoneNumbers: 275,
    uniqueFaxNumbers: 26,
    uniqueMailAddress: 298,
    facebookAccounts: 1,
    twitterAccounts: 1,
    price: 14,
    tollFreeNumbers: 1,
    uniqueWebsites: 87,
    uniqueJobTitles: 104,
    numberOfSic2: 18,
    metaTitle: "Guam Business List 2022 - Guam Company Database",
    metaDescription:
      "Our Company Provide Fresh Guam Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Guam Sample.csv",
  },
  {
    url: "/hawaii-business-list/",
    state: "Hawaii",
    directContacts: 136136,
    uniqueCompanies: 102707,
    uniqueTelephoneNumbers: 87998,
    uniqueFaxNumbers: 7951,
    uniqueMailAddress: 79666,
    facebookAccounts: 701,
    twitterAccounts: 570,
    price: 59,
    tollFreeNumbers: 1042,
    uniqueWebsites: 24628,
    uniqueJobTitles: 404,
    numberOfSic2: 84,
    metaTitle: "Hawaii Business List 2022 - Hawaii Company Database",
    metaDescription:
      "Our Company Provide Fresh Hawaii Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Hawaii Sample.csv",
  },
  {
    url: "/iowa-business-list/",
    state: "Iowa",
    directContacts: 504160,
    uniqueCompanies: 278939,
    uniqueTelephoneNumbers: 246664,
    uniqueFaxNumbers: 19254,
    uniqueMailAddress: 226766,
    facebookAccounts: 1140,
    twitterAccounts: 694,
    price: 96,
    tollFreeNumbers: 4946,
    uniqueWebsites: 52744,
    uniqueJobTitles: 494,
    numberOfSic2: 87,
    metaTitle: "Iowa Business List 2022 - Iowa Company Database",
    metaDescription:
      "Our Company Provide Fresh Iowa Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Iowa Sample.csv",
  },
  {
    url: "/idaho-business-list/",
    state: "Idaho",
    directContacts: 239071,
    uniqueCompanies: 148019,
    uniqueTelephoneNumbers: 127665,
    uniqueFaxNumbers: 9066,
    uniqueMailAddress: 124216,
    facebookAccounts: 1127,
    twitterAccounts: 647,
    price: 74,
    tollFreeNumbers: 1858,
    uniqueWebsites: 31049,
    uniqueJobTitles: 430,
    numberOfSic2: 88,
    metaTitle: "Idaho Business List 2022 - Idaho Company Database",
    metaDescription:
      "Our Company Provide Fresh Idaho Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Idaho Sample.csv",
  },
  {
    url: "/illinois-business-list/",
    state: "Illinois",
    directContacts: 2086261,
    uniqueCompanies: 1016179,
    uniqueTelephoneNumbers: 906069,
    uniqueFaxNumbers: 74953,
    uniqueMailAddress: 826306,
    facebookAccounts: 6726,
    twitterAccounts: 5047,
    price: 224,
    tollFreeNumbers: 11394,
    uniqueWebsites: 224680,
    uniqueJobTitles: 579,
    numberOfSic2: 88,
    metaTitle: "Illinois Business List 2022 - Illinois Company Database",
    metaDescription:
      "Our Company Provide Fresh Illinois Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Illinois Sample.csv",
  },
  {
    url: "/indiana-business-list/",
    state: "Indiana",
    directContacts: 892033,
    uniqueCompanies: 489150,
    uniqueTelephoneNumbers: 430972,
    uniqueFaxNumbers: 36635,
    uniqueMailAddress: 416082,
    facebookAccounts: 3030,
    twitterAccounts: 2131,
    price: 149,
    tollFreeNumbers: 8405,
    uniqueWebsites: 100662,
    uniqueJobTitles: 537,
    numberOfSic2: 87,
    metaTitle: "Indiana Business List 2022 - Indiana Company Database",
    metaDescription:
      "Our Company Provide Fresh Indiana Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Indiana Sample.csv",
  },
  {
    url: "/kansas-business-list/",
    state: "Kansas",
    directContacts: 362469,
    uniqueCompanies: 239403,
    uniqueTelephoneNumbers: 212338,
    uniqueFaxNumbers: 14870,
    uniqueMailAddress: 195250,
    facebookAccounts: 1458,
    twitterAccounts: 967,
    price: 81,
    tollFreeNumbers: 3923,
    uniqueWebsites: 49189,
    uniqueJobTitles: 477,
    numberOfSic2: 87,
    metaTitle: "Kansas Business List 2022 - Kansas Company Database",
    metaDescription:
      "Our Company Provide Fresh Kansas Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Kansas Sample.csv",
  },
  {
    url: "/kentucky-business-list/",
    state: "Kentucky",
    directContacts: 279329,
    uniqueCompanies: 70984,
    uniqueTelephoneNumbers: 58531,
    uniqueFaxNumbers: 24094,
    uniqueMailAddress: 59685,
    facebookAccounts: 84,
    twitterAccounts: 57,
    price: 96,
    tollFreeNumbers: 4990,
    uniqueWebsites: 25591,
    uniqueJobTitles: 504,
    numberOfSic2: 87,
    metaTitle: "Kentucky Business List 2022 - Kentucky Company Database",
    metaDescription:
      "Our Company Provide Fresh Kentucky Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Kentucky Sample.csv",
  },
  {
    url: "/louisiana-business-list/",
    state: "Louisiana",
    directContacts: 396382,
    uniqueCompanies: 227514,
    uniqueTelephoneNumbers: 201154,
    uniqueFaxNumbers: 26861,
    uniqueMailAddress: 201727,
    facebookAccounts: 704,
    twitterAccounts: 487,
    price: 96,
    tollFreeNumbers: 5463,
    uniqueWebsites: 41290,
    uniqueJobTitles: 502,
    numberOfSic2: 87,
    metaTitle: "Louisiana Business List 2022 - Louisiana Company Database",
    metaDescription:
      "Our Company Provide Fresh Louisiana Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Louisiana Sample.csv",
  },
  {
    url: "/massachusetts-business-list/",
    state: "Massachusetts",
    directContacts: 1513984,
    uniqueCompanies: 635085,
    uniqueTelephoneNumbers: 538158,
    uniqueFaxNumbers: 45093,
    uniqueMailAddress: 408934,
    facebookAccounts: "Data",
    twitterAccounts: 4200,
    price: 3052,
    tollFreeNumbers: 7721,
    uniqueWebsites: 156491,
    uniqueJobTitles: 567,
    numberOfSic2: 87,
    metaTitle:
      "Massachusetts Business List 2022 - Massachusetts Company Database",
    metaDescription:
      "Our Company Provide Fresh Massachusetts Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Massachusetts Sample.csv",
  },
  {
    url: "/maryland-business-list/",
    state: "Maryland",
    directContacts: 1003700,
    uniqueCompanies: 532842,
    uniqueTelephoneNumbers: 471178,
    uniqueFaxNumbers: 32728,
    uniqueMailAddress: 438435,
    facebookAccounts: 3398,
    twitterAccounts: 2508,
    price: 149,
    tollFreeNumbers: 5826,
    uniqueWebsites: 111044,
    uniqueJobTitles: 548,
    numberOfSic2: 88,
    metaTitle: "Maryland Business List 2022 - Maryland Company Database",
    metaDescription:
      "Our Company Provide Fresh Maryland Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Maryland Sample.csv",
  },
  {
    url: "/maine-business-list/",
    state: "Maine",
    directContacts: 200296,
    uniqueCompanies: 129368,
    uniqueTelephoneNumbers: 108049,
    uniqueFaxNumbers: 8860,
    uniqueMailAddress: 93515,
    facebookAccounts: 883,
    twitterAccounts: 505,
    price: 74,
    tollFreeNumbers: 2338,
    uniqueWebsites: 30983,
    uniqueJobTitles: 452,
    numberOfSic2: 85,
    metaTitle: "Maine Business List 2022 - Maine Company Database",
    metaDescription:
      "Our Company Provide Fresh Maine Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Maine Sample.csv",
  },
  {
    url: "/michigan-business-list/",
    state: "Michigan",
    directContacts: 1444341,
    uniqueCompanies: 822948,
    uniqueTelephoneNumbers: 727071,
    uniqueFaxNumbers: 54971,
    uniqueMailAddress: 696716,
    facebookAccounts: 5095,
    twitterAccounts: 3289,
    price: 171,
    tollFreeNumbers: 10523,
    uniqueWebsites: 161474,
    uniqueJobTitles: 558,
    numberOfSic2: 87,
    metaTitle: "Michigan Business List 2022 - Michigan Company Database",
    metaDescription:
      "Our Company Provide Fresh Michigan Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Michigan Sample.csv",
  },
  {
    url: "/minnesota-business-list/",
    state: "Minnesota",
    directContacts: 1039777,
    uniqueCompanies: 500096,
    uniqueTelephoneNumbers: 433960,
    uniqueFaxNumbers: 35416,
    uniqueMailAddress: 410433,
    facebookAccounts: 3075,
    twitterAccounts: 2148,
    price: 149,
    tollFreeNumbers: 8172,
    uniqueWebsites: 110150,
    uniqueJobTitles: 549,
    numberOfSic2: 88,
    metaTitle: "Minnesota Business List 2022 - Minnesota Company Database",
    metaDescription:
      "Our Company Provide Fresh Minnesota Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Minnesota Sample.csv",
  },
  {
    url: "/missouri-business-list/",
    state: "Missouri",
    directContacts: 896513,
    uniqueCompanies: 490434,
    uniqueTelephoneNumbers: 434194,
    uniqueFaxNumbers: 33270,
    uniqueMailAddress: 407154,
    facebookAccounts: 3252,
    twitterAccounts: 2130,
    price: 149,
    tollFreeNumbers: 7189,
    uniqueWebsites: 98908,
    uniqueJobTitles: 536,
    numberOfSic2: 89,
    metaTitle: "Missouri Business List 2022 - Missouri Company Database",
    metaDescription:
      "Our Company Provide Fresh Missouri Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Missouri Sample.csv",
  },
  {
    url: "/mississippi-business-list/",
    state: "Mississippi",
    directContacts: 310458,
    uniqueCompanies: 224424,
    uniqueTelephoneNumbers: 204782,
    uniqueFaxNumbers: 13233,
    uniqueMailAddress: 194148,
    facebookAccounts: 837,
    twitterAccounts: 553,
    price: 74,
    tollFreeNumbers: 2649,
    uniqueWebsites: 33079,
    uniqueJobTitles: 457,
    numberOfSic2: 86,
    metaTitle: "Mississippi Business List 2022 - Mississippi Company Database",
    metaDescription:
      "Our Company Provide Fresh Mississippi Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Mississippi Sample.csv",
  },
  {
    url: "/montana-business-list/",
    state: "Montana",
    directContacts: 153979,
    uniqueCompanies: 112150,
    uniqueTelephoneNumbers: 96368,
    uniqueFaxNumbers: 7189,
    uniqueMailAddress: 89689,
    facebookAccounts: 658,
    twitterAccounts: 353,
    price: 59,
    tollFreeNumbers: 1896,
    uniqueWebsites: 23728,
    uniqueJobTitles: 427,
    numberOfSic2: 87,
    metaTitle: "Montana Business List 2022 - Montana Company Database",
    metaDescription:
      "Our Company Provide Fresh Montana Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Montana Sample.csv",
  },
  {
    url: "/north-carolina-business-list/",
    state: "North Carolina",
    directContacts: 1321921,
    uniqueCompanies: 788237,
    uniqueTelephoneNumbers: 721504,
    uniqueFaxNumbers: 49775,
    uniqueMailAddress: 675751,
    facebookAccounts: 6096,
    twitterAccounts: 4272,
    price: 149,
    tollFreeNumbers: 9595,
    uniqueWebsites: 159027,
    uniqueJobTitles: 554,
    numberOfSic2: 89,
    metaTitle:
      "North Carolina Business List 2022 - North Carolina Company Database",
    metaDescription:
      "Our Company Provide Fresh North Carolina Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "North Carolina Sample.csv",
  },
  {
    url: "/north-dakota-business-list/",
    state: "North Dakota",
    directContacts: 124021,
    uniqueCompanies: 79345,
    uniqueTelephoneNumbers: 68259,
    uniqueFaxNumbers: 5177,
    uniqueMailAddress: 63591,
    facebookAccounts: 306,
    twitterAccounts: 197,
    price: 59,
    tollFreeNumbers: 1682,
    uniqueWebsites: 14162,
    uniqueJobTitles: 428,
    numberOfSic2: 87,
    metaTitle:
      "North Dakota Business List 2022 - North Dakota Company Database",
    metaDescription:
      "Our Company Provide Fresh North Dakota Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "North Dakota Sample.csv",
  },
  {
    url: "/nebraska-business-list/",
    state: "Nebraska",
    directContacts: 238413,
    uniqueCompanies: 161529,
    uniqueTelephoneNumbers: 143269,
    uniqueFaxNumbers: 8807,
    uniqueMailAddress: 132932,
    facebookAccounts: 939,
    twitterAccounts: 605,
    price: 74,
    tollFreeNumbers: 2715,
    uniqueWebsites: 31532,
    uniqueJobTitles: 390,
    numberOfSic2: 85,
    metaTitle: "Nebraska Business List 2022 - Nebraska Company Database",
    metaDescription:
      "Our Company Provide Fresh Nebraska Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Nebraska Sample.csv",
  },
  {
    url: "/new-hampshire-business-list/",
    state: "New Hampshire",
    directContacts: 242251,
    uniqueCompanies: 144518,
    uniqueTelephoneNumbers: 118224,
    uniqueFaxNumbers: 9789,
    uniqueMailAddress: 103093,
    facebookAccounts: 1204,
    twitterAccounts: 728,
    price: 81,
    tollFreeNumbers: 2263,
    uniqueWebsites: 36946,
    uniqueJobTitles: 472,
    numberOfSic2: 86,
    metaTitle:
      "New Hampshire Business List 2022 - New Hampshire Company Database",
    metaDescription:
      "Our Company Provide Fresh New Hampshire Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "New Hampshire Sample.csv",
  },
  {
    url: "/new-jersey-business-list/",
    state: "New Jersey",
    directContacts: 1409632,
    uniqueCompanies: 808681,
    uniqueTelephoneNumbers: 717753,
    uniqueFaxNumbers: 49375,
    uniqueMailAddress: 586864,
    facebookAccounts: 5784,
    twitterAccounts: 4296,
    price: 171,
    tollFreeNumbers: 7419,
    uniqueWebsites: 167468,
    uniqueJobTitles: 546,
    numberOfSic2: 89,
    metaTitle: "New Jersey Business List 2022 - New Jersey Company Database",
    metaDescription:
      "Our Company Provide Fresh New Jersey Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "New Jersey Sample.csv",
  },
  {
    url: "/new-mexico-business-list/",
    state: "New Mexico",
    directContacts: 242760,
    uniqueCompanies: 166317,
    uniqueTelephoneNumbers: 144182,
    uniqueFaxNumbers: 10260,
    uniqueMailAddress: 132824,
    facebookAccounts: 958,
    twitterAccounts: 599,
    price: 74,
    tollFreeNumbers: 2100,
    uniqueWebsites: 33332,
    uniqueJobTitles: 459,
    numberOfSic2: 87,
    metaTitle: "New Mexico Business List 2022 - New Mexico Company Database",
    metaDescription:
      "Our Company Provide Fresh New Mexico Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "New Mexico Sample.csv",
  },
  {
    url: "/nevada-business-list/",
    state: "Nevada",
    directContacts: 325800,
    uniqueCompanies: 223300,
    uniqueTelephoneNumbers: 197309,
    uniqueFaxNumbers: 13451,
    uniqueMailAddress: 167071,
    facebookAccounts: 2242,
    twitterAccounts: 1920,
    price: 81,
    tollFreeNumbers: 2305,
    uniqueWebsites: 49558,
    uniqueJobTitles: 468,
    numberOfSic2: 86,
    metaTitle: "Nevada Business List 2022 - Nevada Company Database",
    metaDescription:
      "Our Company Provide Fresh Nevada Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Nevada Sample.csv",
  },
  {
    url: "/new-york-business-list/",
    state: "New York",
    directContacts: 3286551,
    uniqueCompanies: 1649556,
    uniqueTelephoneNumbers: 1437823,
    uniqueFaxNumbers: 93346,
    uniqueMailAddress: 1152969,
    facebookAccounts: 11309,
    twitterAccounts: 9294,
    price: 261,
    tollFreeNumbers: 13126,
    uniqueWebsites: 326160,
    uniqueJobTitles: 590,
    numberOfSic2: 90,
    metaTitle: "New York Business List 2022 - New York Company Database",
    metaDescription:
      "Our Company Provide Fresh New York Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "New York Sample.csv",
  },
  {
    url: "/ohio-business-list/",
    state: "Ohio",
    directContacts: 1378164,
    uniqueCompanies: 572770,
    uniqueTelephoneNumbers: 516199,
    uniqueFaxNumbers: 72730,
    uniqueMailAddress: 496558,
    facebookAccounts: 3090,
    twitterAccounts: 2163,
    price: 201,
    tollFreeNumbers: 15028,
    uniqueWebsites: 129380,
    uniqueJobTitles: 568,
    numberOfSic2: 88,
    metaTitle: "Ohio Business List 2022 - Ohio Company Database",
    metaDescription:
      "Our Company Provide Fresh Ohio Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Ohio Sample.csv",
  },
  {
    url: "/oklahoma-business-list/",
    state: "Oklahoma",
    directContacts: 461391,
    uniqueCompanies: 298496,
    uniqueTelephoneNumbers: 266111,
    uniqueFaxNumbers: 20168,
    uniqueMailAddress: 244069,
    facebookAccounts: 1630,
    twitterAccounts: 1080,
    price: 96,
    tollFreeNumbers: 4431,
    uniqueWebsites: 56295,
    uniqueJobTitles: 498,
    numberOfSic2: 88,
    metaTitle: "Oklahoma Business List 2022 - Oklahoma Company Database",
    metaDescription:
      "Our Company Provide Fresh Oklahoma Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Oklahoma Sample.csv",
  },
  {
    url: "/oregon-business-list/",
    state: "Oregon",
    directContacts: 644032,
    uniqueCompanies: 385544,
    uniqueTelephoneNumbers: 327819,
    uniqueFaxNumbers: 25323,
    uniqueMailAddress: 304495,
    facebookAccounts: 2877,
    twitterAccounts: 1917,
    price: 111,
    tollFreeNumbers: 5040,
    uniqueWebsites: 89390,
    uniqueJobTitles: 504,
    numberOfSic2: 86,
    metaTitle: "Oregon Business List 2022 - Oregon Company Database",
    metaDescription:
      "Our Company Provide Fresh Oregon Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Oregon Sample.csv",
  },
  {
    url: "/pennsylvania-business-list/",
    state: "Pennsylvania",
    directContacts: 1208268,
    uniqueCompanies: 280673,
    uniqueTelephoneNumbers: 249507,
    uniqueFaxNumbers: 77467,
    uniqueMailAddress: 230787,
    facebookAccounts: 533,
    twitterAccounts: 432,
    price: 201,
    tollFreeNumbers: 13964,
    uniqueWebsites: 101033,
    uniqueJobTitles: 569,
    numberOfSic2: 89,
    metaTitle:
      "Pennsylvania Business List 2022 - Pennsylvania Company Database",
    metaDescription:
      "Our Company Provide Fresh Pennsylvania Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Pennsylvania Sample.csv",
  },
  {
    url: "/puerto-rico-business-list/",
    state: "Puerto Rico",
    directContacts: 5569,
    uniqueCompanies: 2361,
    uniqueTelephoneNumbers: 2016,
    uniqueFaxNumbers: 44,
    uniqueMailAddress: 2179,
    facebookAccounts: 1,
    twitterAccounts: 1,
    price: 21,
    tollFreeNumbers: 1,
    uniqueWebsites: 512,
    uniqueJobTitles: 232,
    numberOfSic2: 71,
    metaTitle: "Puerto Rico Business List 2022 - Puerto Rico Company Database",
    metaDescription:
      "Our Company Provide Fresh Puerto Rico Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Puerto Rico Sample.csv",
  },
  {
    url: "/rhode-island-business-list/",
    state: "Rhode Island",
    directContacts: 165504,
    uniqueCompanies: 95286,
    uniqueTelephoneNumbers: 77365,
    uniqueFaxNumbers: 6532,
    uniqueMailAddress: 67364,
    facebookAccounts: 644,
    twitterAccounts: 412,
    price: 74,
    tollFreeNumbers: 1213,
    uniqueWebsites: 22552,
    uniqueJobTitles: 443,
    numberOfSic2: 83,
    metaTitle:
      "Rhode Island Business List 2022 - Rhode Island Company Database",
    metaDescription:
      "Our Company Provide Fresh Rhode Island Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Rhode Island Sample.csv",
  },
  {
    url: "/south-carolina-business-list/",
    state: "South Carolina",
    directContacts: 539321,
    uniqueCompanies: 359218,
    uniqueTelephoneNumbers: 328086,
    uniqueFaxNumbers: 22625,
    uniqueMailAddress: 303023,
    facebookAccounts: 2630,
    twitterAccounts: 1706,
    price: 96,
    tollFreeNumbers: 4525,
    uniqueWebsites: 71122,
    uniqueJobTitles: 492,
    numberOfSic2: 88,
    metaTitle:
      "South Carolina Business List 2022 - South Carolina Company Database",
    metaDescription:
      "Our Company Provide Fresh South Carolina Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "South Carolina Sample.csv",
  },
  {
    url: "/south-dakota-business-list/",
    state: "South Dakota",
    directContacts: 135661,
    uniqueCompanies: 86068,
    uniqueTelephoneNumbers: 73718,
    uniqueFaxNumbers: 5637,
    uniqueMailAddress: 69101,
    facebookAccounts: 381,
    twitterAccounts: 215,
    price: 59,
    tollFreeNumbers: 1731,
    uniqueWebsites: 16511,
    uniqueJobTitles: 428,
    numberOfSic2: 86,
    metaTitle:
      "South Dakota Business List 2022 - South Dakota Company Database",
    metaDescription:
      "Our Company Provide Fresh South Dakota Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "South Dakota Sample.csv",
  },
  {
    url: "/tennessee-business-list/",
    state: "Tennessee",
    directContacts: 903762,
    uniqueCompanies: 517541,
    uniqueTelephoneNumbers: 469165,
    uniqueFaxNumbers: 33192,
    uniqueMailAddress: 432757,
    facebookAccounts: 3362,
    twitterAccounts: 2286,
    price: 134,
    tollFreeNumbers: 6589,
    uniqueWebsites: 98246,
    uniqueJobTitles: 532,
    numberOfSic2: 87,
    metaTitle: "Tennessee Business List 2022 - Tennessee Company Database",
    metaDescription:
      "Our Company Provide Fresh Tennessee Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Tennessee Sample.csv",
  },
  {
    url: "/texas-business-list/",
    state: "Texas",
    directContacts: 3628233,
    uniqueCompanies: 2096320,
    uniqueTelephoneNumbers: 1948845,
    uniqueFaxNumbers: 120863,
    uniqueMailAddress: 1796501,
    facebookAccounts: 14854,
    twitterAccounts: 10879,
    price: 246,
    tollFreeNumbers: 21506,
    uniqueWebsites: 389940,
    uniqueJobTitles: 578,
    numberOfSic2: 89,
    metaTitle: "Texas Business List 2022 - Texas Company Database",
    metaDescription:
      "Our Company Provide Fresh Texas Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Texas Sample.csv",
  },
  {
    url: "/utah-business-list/",
    state: "Utah",
    directContacts: 406634,
    uniqueCompanies: 239825,
    uniqueTelephoneNumbers: 207895,
    uniqueFaxNumbers: 13636,
    uniqueMailAddress: 197141,
    facebookAccounts: 2280,
    twitterAccounts: 1491,
    price: 96,
    tollFreeNumbers: 3235,
    uniqueWebsites: 49405,
    uniqueJobTitles: 481,
    numberOfSic2: 88,
    metaTitle: "Utah Business List 2022 - Utah Company Database",
    metaDescription:
      "Our Company Provide Fresh Utah Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Utah Sample.csv",
  },
  {
    url: "/virginia-business-list/",
    state: "Virginia",
    directContacts: 1383742,
    uniqueCompanies: 691656,
    uniqueTelephoneNumbers: 618912,
    uniqueFaxNumbers: 43170,
    uniqueMailAddress: 576329,
    facebookAccounts: 4806,
    twitterAccounts: 3452,
    price: 171,
    tollFreeNumbers: 7427,
    uniqueWebsites: 146377,
    uniqueJobTitles: 557,
    numberOfSic2: 89,
    metaTitle: "Virginia Business List 2022 - Virginia Company Database",
    metaDescription:
      "Our Company Provide Fresh Virginia Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Virginia Sample.csv",
  },
  {
    url: "/virgin-islands/",
    state: "Virgin Islands",
    directContacts: 2757,
    uniqueCompanies: 367,
    uniqueTelephoneNumbers: 284,
    uniqueFaxNumbers: 103,
    uniqueMailAddress: 297,
    facebookAccounts: 1,
    twitterAccounts: 1,
    price: 21,
    tollFreeNumbers: 33,
    uniqueWebsites: 187,
    uniqueJobTitles: 158,
    numberOfSic2: 55,
    metaTitle:
      "Virgin Islands Business List 2022 - Virgin Islands Company Database",
    metaDescription:
      "Our Company Provide Fresh Virgin Islands Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Virgin Islands Sample.csv",
  },
  {
    url: "/vermont-business-list/",
    state: "Vermont",
    directContacts: 125821,
    uniqueCompanies: 71307,
    uniqueTelephoneNumbers: 58134,
    uniqueFaxNumbers: 4885,
    uniqueMailAddress: 52830,
    facebookAccounts: 432,
    twitterAccounts: 247,
    price: 59,
    tollFreeNumbers: 1329,
    uniqueWebsites: 18211,
    uniqueJobTitles: 418,
    numberOfSic2: 83,
    metaTitle: "Vermont Business List 2022 - Vermont Company Database",
    metaDescription:
      "Our Company Provide Fresh Vermont Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Vermont Sample.csv",
  },
  {
    url: "/washington-company-database/",
    state: "Washington",
    directContacts: 1153489,
    uniqueCompanies: 647931,
    uniqueTelephoneNumbers: 559563,
    uniqueFaxNumbers: 41446,
    uniqueMailAddress: 537531,
    facebookAccounts: 4965,
    twitterAccounts: 3218,
    price: 149,
    tollFreeNumbers: 8330,
    uniqueWebsites: 157385,
    uniqueJobTitles: 547,
    numberOfSic2: 88,
    metaTitle: "Washington Business List 2022 - Washington Company Database",
    metaDescription:
      "Our Company Provide Fresh Washington Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Washington Sample.csv",
  },
  {
    url: "/wisconsin-business-list/",
    state: "Wisconsin",
    directContacts: 972279,
    uniqueCompanies: 481124,
    uniqueTelephoneNumbers: 413467,
    uniqueFaxNumbers: 36145,
    uniqueMailAddress: 391336,
    facebookAccounts: 2978,
    twitterAccounts: 1827,
    price: 149,
    tollFreeNumbers: 8468,
    uniqueWebsites: 106243,
    uniqueJobTitles: 543,
    numberOfSic2: 86,
    metaTitle: "Wisconsin Business List 2022 - Wisconsin Company Database",
    metaDescription:
      "Our Company Provide Fresh Wisconsin Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Wisconsin Sample.csv",
  },
  {
    url: "/west-virginia-business-list/",
    state: "West Virginia",
    directContacts: 175838,
    uniqueCompanies: 122998,
    uniqueTelephoneNumbers: 108801,
    uniqueFaxNumbers: 7511,
    uniqueMailAddress: 97017,
    facebookAccounts: 532,
    twitterAccounts: 325,
    price: 59,
    tollFreeNumbers: 1868,
    uniqueWebsites: 21092,
    uniqueJobTitles: 424,
    numberOfSic2: 87,
    metaTitle:
      "West Virginia Business List 2022 - West Virginia Company Database",
    metaDescription:
      "Our Company Provide Fresh West Virginia Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "West Virginia Sample.csv",
  },
  {
    url: "/wyoming-business-list/",
    state: "Wyoming",
    directContacts: 85252,
    uniqueCompanies: 59738,
    uniqueTelephoneNumbers: 51630,
    uniqueFaxNumbers: 4144,
    uniqueMailAddress: 48585,
    facebookAccounts: 295,
    twitterAccounts: 170,
    price: 36,
    tollFreeNumbers: 988,
    uniqueWebsites: 12519,
    uniqueJobTitles: 380,
    numberOfSic2: 87,
    metaTitle: "Wyoming Business List 2022 - Wyoming Company Database",
    metaDescription:
      "Our Company Provide Fresh Wyoming Business List and Email List for your Email Marketing ,Direct marketing & Telemarketing Campaign",
    sampleFileName: "Wyoming Sample.csv",
  },
];
