export const REALTORS = [
  {
    url: "/alabama-realtors/",
    state: "Alabama",
    directContacts: 22912,
    directEmailAddresses: 22912,
    officeAddresses: 22912,
    officePhoneNumbers: 3246,
    officeFaxNumbers: 1106,
    cellPhones: 10039,
    licenseType: 18028,
    emailDatabasePrice: 45,
    completeDatabasePrice: 73,
    metaTitle: "2022 Updated List of Realtors In Alabama",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Alabama realtors who are likely to work with your business.",
    sampleFileName: "Alabama_Realtors_Sample.csv",
  },
  {
    url: "/alaska-realtors/",
    state: "Alaska",
    directContacts: 2167,
    directEmailAddresses: 2167,
    officeAddresses: 2167,
    officePhoneNumbers: 331,
    officeFaxNumbers: 113,
    cellPhones: 669,
    licenseType: 1475,
    emailDatabasePrice: 18,
    completeDatabasePrice: 31,
    metaTitle: "2022 Updated List of Realtors In Alaska",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Alaska realtors who are likely to work with your business.",
    sampleFileName: "Alaska_Realtors_Sample.csv",
  },
  {
    url: "/arizona-realtors/",
    state: "Arizona",
    directContacts: 57339,
    directEmailAddresses: 57339,
    officeAddresses: 57339,
    officePhoneNumbers: 6398,
    officeFaxNumbers: 4887,
    cellPhones: 43447,
    licenseType: 48818,
    emailDatabasePrice: 119,
    completeDatabasePrice: 200,
    metaTitle: "2022 Updated List of Realtors In Arizona",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Arizona realtors who are likely to work with your business.",
    sampleFileName: "Arizona_Realtors_Sample.csv",
  },
  {
    url: "/arkansas-realtors/",
    state: "Arkansas",
    directContacts: 4994,
    directEmailAddresses: 4994,
    officeAddresses: 4994,
    officePhoneNumbers: 1799,
    officeFaxNumbers: 714,
    cellPhones: 1941,
    licenseType: 1785,
    emailDatabasePrice: 31,
    completeDatabasePrice: 48,
    metaTitle: "2022 Updated List of Realtors In Arkansas",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Arkansas realtors who are likely to work with your business.",
    sampleFileName: "Arkansas_Realtors_Sample.csv",
  },
  {
    url: "/california-realtors/",
    state: "California",
    directContacts: 396932,
    directEmailAddresses: 396932,
    officeAddresses: 396932,
    officePhoneNumbers: 45652,
    officeFaxNumbers: 28339,
    cellPhones: 83158,
    licenseType: 358675,
    emailDatabasePrice: 334,
    completeDatabasePrice: 562,
    metaTitle:
      "2022 Updated California Realtors and Real Estate Agents Email List",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for California realtors who are likely to work with your business.",
    sampleFileName: "California_Realtors_Sample.csv",
  },
  {
    url: "/colorado-realtors/",
    state: "Colorado",
    directContacts: 40659,
    directEmailAddresses: 40659,
    officeAddresses: 40659,
    officePhoneNumbers: 8642,
    officeFaxNumbers: 920,
    cellPhones: 27921,
    licenseType: 14211,
    emailDatabasePrice: 105,
    completeDatabasePrice: 175,
    metaTitle: "2022 Updated List of Realtors In Colorado",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Colorado realtors who are likely to work with your business.",
    sampleFileName: "Colorado_Realtors_Sample.csv",
  },
  {
    url: "/connecticut-realtors/",
    state: "Connecticut",
    directContacts: 20261,
    directEmailAddresses: 20261,
    officeAddresses: 20261,
    officePhoneNumbers: 2856,
    officeFaxNumbers: 2135,
    cellPhones: 12080,
    licenseType: 17090,
    emailDatabasePrice: 55,
    completeDatabasePrice: 98,
    metaTitle: "2022 Updated List of Realtors In Connecticut",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Connecticut realtors who are likely to work with your business.",
    sampleFileName: "Connecticut_Realtors_Sample.csv",
  },
  {
    url: "/delaware-realtors/",
    state: "Delaware",
    directContacts: 6320,
    directEmailAddresses: 6320,
    officeAddresses: 6320,
    officePhoneNumbers: 917,
    officeFaxNumbers: 279,
    cellPhones: 1796,
    licenseType: 1020,
    emailDatabasePrice: 38,
    completeDatabasePrice: 62,
    metaTitle: "2022 Updated List of Realtors In Delaware",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Delaware realtors who are likely to work with your business.",
    sampleFileName: "Delaware_Realtors_Sample.csv",
  },
  {
    url: "/florida-realtors/",
    state: "Florida",
    directContacts: 387827,
    directEmailAddresses: 387827,
    officeAddresses: 387827,
    officePhoneNumbers: 188472,
    officeFaxNumbers: 10237,
    cellPhones: 72565,
    licenseType: 349386,
    emailDatabasePrice: 295,
    completeDatabasePrice: 492,
    metaTitle:
      "2022 Updated Florida Realtors and Real Estate Agents Email List",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Florida realtors who are likely to work with your business.",
    sampleFileName: "Florida_Realtors_Sample.csv",
  },
  {
    url: "/realtors-georgia/",
    state: "Georgia",
    directContacts: 99011,
    directEmailAddresses: 99011,
    officeAddresses: 99011,
    officePhoneNumbers: 7508,
    officeFaxNumbers: 4629,
    cellPhones: 34321,
    licenseType: 87230,
    emailDatabasePrice: 147,
    completeDatabasePrice: 246,
    metaTitle: "2022 Updated List of Realtors In Georgia",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Georgia realtors who are likely to work with your business.",
    sampleFileName: "Georgia_Realtors_Sample.csv",
  },
  {
    url: "/hawaii-realtors/",
    state: "Hawaii",
    directContacts: 6528,
    directEmailAddresses: 6528,
    officeAddresses: 6528,
    officePhoneNumbers: 2074,
    officeFaxNumbers: 1093,
    cellPhones: 2886,
    licenseType: 168,
    emailDatabasePrice: 38,
    completeDatabasePrice: 62,
    metaTitle: "2022 Updated List of Realtors In Hawaii",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Hawaii realtors who are likely to work with your business.",
    sampleFileName: "Hawaii_Realtors_Sample.csv",
  },
  {
    url: "/idaho-realtors/",
    state: "Idaho",
    directContacts: 10123,
    directEmailAddresses: 10123,
    officeAddresses: 10123,
    officePhoneNumbers: 1314,
    officeFaxNumbers: 516,
    cellPhones: 6599,
    licenseType: 6513,
    emailDatabasePrice: 48,
    completeDatabasePrice: 80,
    metaTitle: "2022 Updated List of Realtors In Idaho",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Idaho realtors who are likely to work with your business.",
    sampleFileName: "Idaho_Realtors_Sample.csv",
  },
  {
    url: "/illinois-realtors/",
    state: "Illinois",
    directContacts: 61712,
    directEmailAddresses: 61712,
    officeAddresses: 61712,
    officePhoneNumbers: 31324,
    officeFaxNumbers: 2828,
    cellPhones: 4810,
    licenseType: 37229,
    emailDatabasePrice: 105,
    completeDatabasePrice: 175,
    metaTitle: "2022 Updated List of Realtors In Illinois",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Illinois realtors who are likely to work with your business.",
    sampleFileName: "Illinois_Realtors_Sample.csv",
  },
  {
    url: "/indiana-realtors/",
    state: "Indiana",
    directContacts: 13599,
    directEmailAddresses: 13599,
    officeAddresses: 13599,
    officePhoneNumbers: 5314,
    officeFaxNumbers: 1664,
    cellPhones: 5069,
    licenseType: 638,
    emailDatabasePrice: 52,
    completeDatabasePrice: 84,
    metaTitle: "2022 Updated List of Realtors In Indiana",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Indiana realtors who are likely to work with your business.",
    sampleFileName: "Indiana_Realtors_Sample.csv",
  },
  {
    url: "/iowa-realtors/",
    state: "Iowa",
    directContacts: 6925,
    directEmailAddresses: 6925,
    officeAddresses: 6925,
    officePhoneNumbers: 2401,
    officeFaxNumbers: 667,
    cellPhones: 2480,
    licenseType: 1243,
    emailDatabasePrice: 34,
    completeDatabasePrice: 55,
    metaTitle: "2022 Updated List of Realtors In Iowa",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Iowa realtors who are likely to work with your business.",
    sampleFileName: "Iowa_Realtors_Sample.csv",
  },
  {
    url: "/kansas-realtors/",
    state: "Kansas",
    directContacts: 7063,
    directEmailAddresses: 7063,
    officeAddresses: 7063,
    officePhoneNumbers: 2025,
    officeFaxNumbers: 653,
    cellPhones: 3262,
    licenseType: 405,
    emailDatabasePrice: 38,
    completeDatabasePrice: 59,
    metaTitle: "2022 Updated List of Realtors In Kansas",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Kansas realtors who are likely to work with your business.",
    sampleFileName: "Kansas_Realtors_Sample.csv",
  },
  {
    url: "/kentucky-realtors/",
    state: "Kentucky",
    directContacts: 9519,
    directEmailAddresses: 9519,
    officeAddresses: 9519,
    officePhoneNumbers: 2956,
    officeFaxNumbers: 929,
    cellPhones: 3665,
    licenseType: 2319,
    emailDatabasePrice: 45,
    completeDatabasePrice: 70,
    metaTitle: "2022 Updated List of Realtors In Kentucky",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Kentucky realtors who are likely to work with your business.",
    sampleFileName: "Kentucky_Realtors_Sample.csv",
  },
  {
    url: "/louisiana-realtors/",
    state: "Louisiana",
    directContacts: 11928,
    directEmailAddresses: 11928,
    officeAddresses: 11928,
    officePhoneNumbers: 3084,
    officeFaxNumbers: 1070,
    cellPhones: 4422,
    licenseType: 2915,
    emailDatabasePrice: 48,
    completeDatabasePrice: 80,
    metaTitle: "2022 Updated List of Realtors In Louisiana",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Louisiana realtors who are likely to work with your business.",
    sampleFileName: "Louisiana_Realtors_Sample.csv",
  },
  {
    url: "/maine-realtors/",
    state: "Maine",
    directContacts: 6328,
    directEmailAddresses: 6328,
    officeAddresses: 6328,
    officePhoneNumbers: 891,
    officeFaxNumbers: 759,
    cellPhones: 4273,
    licenseType: 4701,
    emailDatabasePrice: 31,
    completeDatabasePrice: 48,
    metaTitle: "2022 Updated List of Realtors In Maine",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Maine realtors who are likely to work with your business.",
    sampleFileName: "Maine_Realtors_Sample.csv",
  },
  {
    url: "/maryland-realtors/",
    state: "Maryland",
    directContacts: 45239,
    directEmailAddresses: 45239,
    officeAddresses: 45239,
    officePhoneNumbers: 4368,
    officeFaxNumbers: 1924,
    cellPhones: 10315,
    licenseType: 31999,
    emailDatabasePrice: 91,
    completeDatabasePrice: 154,
    metaTitle: "2022 Updated List of Realtors In Maryland",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Maryland realtors who are likely to work with your business.",
    sampleFileName: "Maryland_Realtors_Sample.csv",
  },
  {
    url: "/massachusetts-realtors/",
    state: "Massachusetts",
    directContacts: 24291,
    directEmailAddresses: 24291,
    officeAddresses: 24291,
    officePhoneNumbers: 5134,
    officeFaxNumbers: 1837,
    cellPhones: 7129,
    licenseType: 15402,
    emailDatabasePrice: 62,
    completeDatabasePrice: 108,
    metaTitle: "2022 Updated List of Realtors In Massachusetts",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Massachusetts realtors who are likely to work with your business.",
    sampleFileName: "Massachusetts_Realtors_Sample.csv",
  },
  {
    url: "/michigan-realtors/",
    state: "Michigan",
    directContacts: 67475,
    directEmailAddresses: 67475,
    officeAddresses: 67475,
    officePhoneNumbers: 6615,
    officeFaxNumbers: 3850,
    cellPhones: 19087,
    licenseType: 56053,
    emailDatabasePrice: 91,
    completeDatabasePrice: 154,
    metaTitle: "2022 Updated List of Realtors In Michigan",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Michigan realtors who are likely to work with your business.",
    sampleFileName: "Michigan_Realtors_Sample.csv",
  },
  {
    url: "/minnesota-realtors/",
    state: "Minnesota",
    directContacts: 22923,
    directEmailAddresses: 22923,
    officeAddresses: 22923,
    officePhoneNumbers: 4400,
    officeFaxNumbers: 2457,
    cellPhones: 14807,
    licenseType: 16060,
    emailDatabasePrice: 59,
    completeDatabasePrice: 94,
    metaTitle: "2022 Updated List of Realtors In Minnesota",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Minnesota realtors who are likely to work with your business.",
    sampleFileName: "Minnesota_Realtors_Sample.csv",
  },
  {
    url: "/mississippi-realtors/",
    state: "Mississippi",
    directContacts: 4581,
    directEmailAddresses: 4581,
    officeAddresses: 4581,
    officePhoneNumbers: 1600,
    officeFaxNumbers: 696,
    cellPhones: 1424,
    licenseType: 1419,
    emailDatabasePrice: 31,
    completeDatabasePrice: 48,
    metaTitle: "2022 Updated List of Realtors In Mississippi",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Mississippi realtors who are likely to work with your business.",
    sampleFileName: "Mississippi_Realtors_Sample.csv",
  },
  {
    url: "/missouri-realtors/",
    state: "Missouri",
    directContacts: 26356,
    directEmailAddresses: 26356,
    officeAddresses: 26356,
    officePhoneNumbers: 4789,
    officeFaxNumbers: 1173,
    cellPhones: 9108,
    licenseType: 20891,
    emailDatabasePrice: 62,
    completeDatabasePrice: 108,
    metaTitle: "2022 Updated List of Realtors In Missouri",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Missouri realtors who are likely to work with your business.",
    sampleFileName: "Missouri_Realtors_Sample.csv",
  },
  {
    url: "/montana-realtors/",
    state: "Montana",
    directContacts: 2876,
    directEmailAddresses: 2876,
    officeAddresses: 2876,
    officePhoneNumbers: 1339,
    officeFaxNumbers: 500,
    cellPhones: 1056,
    licenseType: 80,
    emailDatabasePrice: 24,
    completeDatabasePrice: 38,
    metaTitle: "2022 Updated List of Realtors In Montana",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Montana realtors who are likely to work with your business.",
    sampleFileName: "Montana_Realtors_Sample.csv",
  },
  {
    url: "/nebraska-realtors/",
    state: "Nebraska",
    directContacts: 3613,
    directEmailAddresses: 3613,
    officeAddresses: 3613,
    officePhoneNumbers: 1140,
    officeFaxNumbers: 287,
    cellPhones: 1346,
    licenseType: 102,
    emailDatabasePrice: 27,
    completeDatabasePrice: 45,
    metaTitle: "2022 Updated List of Realtors In Nebraska",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Nebraska realtors who are likely to work with your business.",
    sampleFileName: "Nebraska_Realtors_Sample.csv",
  },
  {
    url: "/nevada-realtors/",
    state: "Nevada",
    directContacts: 23479,
    directEmailAddresses: 23479,
    officeAddresses: 23479,
    officePhoneNumbers: 2532,
    officeFaxNumbers: 1192,
    cellPhones: 17584,
    licenseType: 19551,
    emailDatabasePrice: 55,
    completeDatabasePrice: 98,
    metaTitle: "2022 Updated List of Realtors In Nevada",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Nevada realtors who are likely to work with your business.",
    sampleFileName: "Nevada_Realtors_Sample.csv",
  },
  {
    url: "/new-hampshire-realtors/",
    state: "New Hampshire",
    directContacts: 8313,
    directEmailAddresses: 8313,
    officeAddresses: 8313,
    officePhoneNumbers: 1772,
    officeFaxNumbers: 721,
    cellPhones: 2045,
    licenseType: 4651,
    emailDatabasePrice: 34,
    completeDatabasePrice: 52,
    metaTitle: "2022 Updated List of Realtors In New Hampshire",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for New Hampshire realtors who are likely to work with your business.",
    sampleFileName: "New Hampshire_Realtors_Sample.csv",
  },
  {
    url: "/new-jersey-realtors/",
    state: "New Jersey",
    directContacts: 68794,
    directEmailAddresses: 68794,
    officeAddresses: 68794,
    officePhoneNumbers: 5450,
    officeFaxNumbers: 3325,
    cellPhones: 18044,
    licenseType: 41577,
    emailDatabasePrice: 154,
    completeDatabasePrice: 256,
    metaTitle: "2022 Updated List of Realtors In New Jersey",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for New Jersey realtors who are likely to work with your business.",
    sampleFileName: "New Jersey_Realtors_Sample.csv",
  },
  {
    url: "/new-mexico-realtors/",
    state: "New Mexico",
    directContacts: 5489,
    directEmailAddresses: 5489,
    officeAddresses: 5489,
    officePhoneNumbers: 1925,
    officeFaxNumbers: 882,
    cellPhones: 2030,
    licenseType: 170,
    emailDatabasePrice: 31,
    completeDatabasePrice: 52,
    metaTitle: "2022 Updated List of Realtors In New Mexico",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for New Mexico realtors who are likely to work with your business.",
    sampleFileName: "New Mexico_Realtors_Sample.csv",
  },
  {
    url: "/new-york-realtors/",
    state: "New York",
    directContacts: 75029,
    directEmailAddresses: 75029,
    officeAddresses: 75029,
    officePhoneNumbers: 10544,
    officeFaxNumbers: 6228,
    cellPhones: 13653,
    licenseType: 59158,
    emailDatabasePrice: 136,
    completeDatabasePrice: 228,
    metaTitle:
      "2022 Updated New York Realtors & New York Real Estate Agents Email List",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for New York realtors who are likely to work with your business.",
    sampleFileName: "New York_Realtors_Sample.csv",
  },
  {
    url: "/north-carolina-realtors/",
    state: "North Carolina",
    directContacts: 82455,
    directEmailAddresses: 82455,
    officeAddresses: 82455,
    officePhoneNumbers: 28750,
    officeFaxNumbers: 10658,
    cellPhones: 38038,
    licenseType: 74457,
    emailDatabasePrice: 140,
    completeDatabasePrice: 235,
    metaTitle: "2022 Updated List of Realtors In North Carolina",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for North Carolina realtors who are likely to work with your business.",
    sampleFileName: "North Carolina_Realtors_Sample.csv",
  },
  {
    url: "/north-dakota-realtors/",
    state: "North Dakota",
    directContacts: 2612,
    directEmailAddresses: 2612,
    officeAddresses: 2612,
    officePhoneNumbers: 334,
    officeFaxNumbers: 42,
    cellPhones: 244,
    licenseType: 2229,
    emailDatabasePrice: 18,
    completeDatabasePrice: 31,
    metaTitle: "2022 Updated List of Realtors In North Dakota",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for North Dakota realtors who are likely to work with your business.",
    sampleFileName: "North Dakota_Realtors_Sample.csv",
  },
  {
    url: "/ohio-realtors/",
    state: "Ohio",
    directContacts: 53397,
    directEmailAddresses: 53397,
    officeAddresses: 53397,
    officePhoneNumbers: 4445,
    officeFaxNumbers: 2156,
    cellPhones: 11397,
    licenseType: 45039,
    emailDatabasePrice: 119,
    completeDatabasePrice: 200,
    metaTitle: "2022 Updated List of Realtors In Ohio",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Ohio realtors who are likely to work with your business.",
    sampleFileName: "Ohio_Realtors_Sample.csv",
  },
  {
    url: "/oklahoma-realtors/",
    state: "Oklahoma",
    directContacts: 15818,
    directEmailAddresses: 15818,
    officeAddresses: 15818,
    officePhoneNumbers: 2116,
    officeFaxNumbers: 1020,
    cellPhones: 10131,
    licenseType: 12746,
    emailDatabasePrice: 38,
    completeDatabasePrice: 62,
    metaTitle: "2022 Updated List of Realtors In Oklahoma",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Oklahoma realtors who are likely to work with your business.",
    sampleFileName: "Oklahoma_Realtors_Sample.csv",
  },
  {
    url: "/oregon-realtors/",
    state: "Oregon",
    directContacts: 17971,
    directEmailAddresses: 17971,
    officeAddresses: 17971,
    officePhoneNumbers: 3056,
    officeFaxNumbers: 1107,
    cellPhones: 6575,
    licenseType: 14878,
    emailDatabasePrice: 52,
    completeDatabasePrice: 84,
    metaTitle: "2022 Updated List of Realtors In Oregon",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Oregon realtors who are likely to work with your business.",
    sampleFileName: "Oregon_Realtors_Sample.csv",
  },
  {
    url: "/pennsylvania-realtors/",
    state: "Pennsylvania",
    directContacts: 65208,
    directEmailAddresses: 65208,
    officeAddresses: 65208,
    officePhoneNumbers: 17094,
    officeFaxNumbers: 3282,
    cellPhones: 17330,
    licenseType: 53185,
    emailDatabasePrice: 112,
    completeDatabasePrice: 189,
    metaTitle: "2022 Updated List of Realtors In Pennsylvania",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Pennsylvania realtors who are likely to work with your business.",
    sampleFileName: "Pennsylvania_Realtors_Sample.csv",
  },
  {
    url: "/rhode-island-realtors/",
    state: "Rhode Island",
    directContacts: 4050,
    directEmailAddresses: 4050,
    officeAddresses: 4050,
    officePhoneNumbers: 1375,
    officeFaxNumbers: 408,
    cellPhones: 1679,
    licenseType: 399,
    emailDatabasePrice: 27,
    completeDatabasePrice: 45,
    metaTitle: "2022 Updated List of Realtors In Rhode Island",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Rhode Island realtors who are likely to work with your business.",
    sampleFileName: "Rhode Island_Realtors_Sample.csv",
  },
  {
    url: "/south-carolina-realtors/",
    state: "South Carolina",
    directContacts: 24769,
    directEmailAddresses: 24769,
    officeAddresses: 24769,
    officePhoneNumbers: 3888,
    officeFaxNumbers: 1061,
    cellPhones: 7582,
    licenseType: 18638,
    emailDatabasePrice: 70,
    completeDatabasePrice: 115,
    metaTitle: "2022 Updated List of Realtors In South Carolina",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for South Carolina realtors who are likely to work with your business.",
    sampleFileName: "South Carolina_Realtors_Sample.csv",
  },
  {
    url: "/south-dakota-realtors/",
    state: "South Dakota",
    directContacts: 1835,
    directEmailAddresses: 1835,
    officeAddresses: 1835,
    officePhoneNumbers: 517,
    officeFaxNumbers: 201,
    cellPhones: 801,
    licenseType: 63,
    emailDatabasePrice: 18,
    completeDatabasePrice: 31,
    metaTitle: "2022 Updated List of Realtors In South Dakota",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for South Dakota realtors who are likely to work with your business.",
    sampleFileName: "South Dakota_Realtors_Sample.csv",
  },
  {
    url: "/tennessee-realtors/",
    state: "Tennessee",
    directContacts: 47169,
    directEmailAddresses: 47169,
    officeAddresses: 47169,
    officePhoneNumbers: 24297,
    officeFaxNumbers: 2126,
    cellPhones: 16390,
    licenseType: 18135,
    emailDatabasePrice: 87,
    completeDatabasePrice: 136,
    metaTitle: "2022 Updated List of Realtors In Tennessee",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Tennessee realtors who are likely to work with your business.",
    sampleFileName: "Tennessee_Realtors_Sample.csv",
  },
  {
    url: "/texas-realtors/",
    state: "Texas",
    directContacts: 240063,
    directEmailAddresses: 240063,
    officeAddresses: 240063,
    officePhoneNumbers: 84307,
    officeFaxNumbers: 4147,
    cellPhones: 131852,
    licenseType: 201300,
    emailDatabasePrice: 210,
    completeDatabasePrice: 351,
    metaTitle: "2022 Updated List of Realtors In Texas",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Texas realtors who are likely to work with your business.",
    sampleFileName: "Texas_Realtors_Sample.csv",
  },
  {
    url: "/utah-realtors/",
    state: "Utah",
    directContacts: 13707,
    directEmailAddresses: 13707,
    officeAddresses: 13707,
    officePhoneNumbers: 3166,
    officeFaxNumbers: 1324,
    cellPhones: 4446,
    licenseType: 3949,
    emailDatabasePrice: 52,
    completeDatabasePrice: 84,
    metaTitle: "2022 Updated List of Realtors In Utah",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Utah realtors who are likely to work with your business.",
    sampleFileName: "Utah_Realtors_Sample.csv",
  },
  {
    url: "/vermont-realtors/",
    state: "Vermont",
    directContacts: 1628,
    directEmailAddresses: 1628,
    officeAddresses: 1628,
    officePhoneNumbers: 562,
    officeFaxNumbers: 162,
    cellPhones: 201,
    licenseType: 1113,
    emailDatabasePrice: 18,
    completeDatabasePrice: 31,
    metaTitle: "2022 Updated List of Realtors In Vermont",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Vermont realtors who are likely to work with your business.",
    sampleFileName: "Vermont_Realtors_Sample.csv",
  },
  {
    url: "/virginia-realtors/",
    state: "Virginia",
    directContacts: 63109,
    directEmailAddresses: 63109,
    officeAddresses: 63109,
    officePhoneNumbers: 5061,
    officeFaxNumbers: 1559,
    cellPhones: 4761,
    licenseType: 51938,
    emailDatabasePrice: 115,
    completeDatabasePrice: 193,
    metaTitle: "2022 Updated List of Realtors In Virginia",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Virginia realtors who are likely to work with your business.",
    sampleFileName: "Virginia_Realtors_Sample.csv",
  },
  {
    url: "/washington-realtors/",
    state: "Washington",
    directContacts: 26832,
    directEmailAddresses: 26832,
    officeAddresses: 26832,
    officePhoneNumbers: 3272,
    officeFaxNumbers: 1989,
    cellPhones: 16535,
    licenseType: 1,
    emailDatabasePrice: 70,
    completeDatabasePrice: 115,
    metaTitle: "2022 Updated List of Realtors In Washington",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Washington realtors who are likely to work with your business.",
    sampleFileName: "Washington_Realtors_Sample.csv",
  },
  {
    url: "/district-of-columbia-realtors/",
    state: "Washington, D.C.",
    directContacts: 4886,
    directEmailAddresses: 4886,
    officeAddresses: 4886,
    officePhoneNumbers: 677,
    officeFaxNumbers: 295,
    cellPhones: 1245,
    licenseType: 2437,
    emailDatabasePrice: 34,
    completeDatabasePrice: 52,
    metaTitle: "2022 Updated List of Realtors In District of Columbia",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Washington, D.C. realtors who are likely to work with your business.",
    sampleFileName: "Washington, D.C._Realtors_Sample.csv",
  },
  {
    url: "/west-virginia-realtors/",
    state: "West Virginia",
    directContacts: 2419,
    directEmailAddresses: 2419,
    officeAddresses: 2419,
    officePhoneNumbers: 685,
    officeFaxNumbers: 268,
    cellPhones: 519,
    licenseType: 192,
    emailDatabasePrice: 23,
    completeDatabasePrice: 34,
    metaTitle: "2022 Updated List of Realtors In West Virginia",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for West Virginia realtors who are likely to work with your business.",
    sampleFileName: "West Virginia_Realtors_Sample.csv",
  },
  {
    url: "/wisconsin-realtors/",
    state: "Wisconsin",
    directContacts: 17126,
    directEmailAddresses: 17126,
    officeAddresses: 17126,
    officePhoneNumbers: 3297,
    officeFaxNumbers: 1339,
    cellPhones: 4347,
    licenseType: 4416,
    emailDatabasePrice: 55,
    completeDatabasePrice: 98,
    metaTitle: "2022 Updated List of Realtors In Wisconsin",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Wisconsin realtors who are likely to work with your business.",
    sampleFileName: "Wisconsin_Realtors_Sample.csv",
  },
  {
    url: "/wyoming-realtors/",
    state: "Wyoming",
    directContacts: 2624,
    directEmailAddresses: 2624,
    officeAddresses: 2624,
    officePhoneNumbers: 558,
    officeFaxNumbers: 121,
    cellPhones: 141,
    licenseType: 2137,
    emailDatabasePrice: 18,
    completeDatabasePrice: 31,
    metaTitle: "2022 Updated List of Realtors In Wyoming",
    metaDescription:
      "Buy Most up-to-date real estate emails and contact details for Wyoming realtors who are likely to work with your business.",
    sampleFileName: "Wyoming_Realtors_Sample.csv",
  },
];
