export enum BUTTON_SIZE_ENUM {
  Small = "small",
  Large = "large",
  Default = "default",
}

export enum FEATURE_CARD_TYPE {
  Info = "info",
  Action = "action",
}

export enum FEATURE_CARD_VARIANT {
  Dark = "dark",
  Light = "light",
}

export enum BUTTON_VARIANT_ENUM {
  Primary = "primary",
  Secondary = "secondary",
  Tertiary = "tertiary",
  Text = "text",
}

export enum DATABASE_MAIN_TYPES {
  COMPANY_DATABASE = "COMPANY_DATABASE",
  REALTOR = "REALTOR",
  JOB_TITLE = "JOB_TITLE",
  INDUSTRY = "INDUSTRY",
  COUNTRY = "COUNTRY",
  CONSUMER = "CONSUMER",
  OTHERS = "OTHERS",
  TARGET = "TARGET",
  COMPANY_DATABASE_OLD = "COMPANY_DATABASE_OLD",
  REALTOR_OLD = "REALTOR_OLD",
}

export enum PAYMENT_STATUS {
  INITIALIZED = "Initialized",
  REQUESTED = "Requested",
  PENDING = "Pending",
  APPROVED = "Approved",
  REJECTED = "Rejected",
}

export enum PAYMENT_METHOD {
  PAYPAL = "Paypal",
  CRYPTO = "Crypto",
  CRYPTO_PLISIO = "Crypto payment using CoinPayments",
  CRYPTO_PLISIO_INITIALIZED = "Crypto payment using CoinPayments - initialized",
}

export enum PAYMENT_CRYPTO_COIN {
  USDT = "USDT",
  USDC = "USDC",
  BITCOIN = "BITCOIN",
}

export enum STATUS {
  Pending = "pending",
  Success = "success",
  Failed = "failed",
}

export enum PRODUCT_MAIN_TYPE_ENUM {
  BY_B2B_EMAILS = "BY_B2B_EMAILS",
  BY_REALTORS = "BY_REALTORS",
  BY_PROFESSION = "BY_PROFESSION",
}

export enum EMAIL_VERIFICATION_TYPE {
  EMAIL_MARKETTING_FREE_SAMPLE = "email_marketting_free_sample",
  FREE_SAMPLE_ON_EVERY_PRODUCT = "free_sample_on_every_product",
}

export enum MAIN_DATABASE_CATEGORIES {
  EMAIL_DATABASE = "EMAIL_DATABASE",
  COMPLETE_DATABASE = "COMPLETE_DATABASE",
}

export enum JOB_TITLE_TYPES {
  DIRECTOR_LEVEL_AND_FINANCE = "DIRECTOR_LEVEL_AND_FINANCE",
  MANAGER_LEVEL_AND_FINANCE = "MANAGER_LEVEL_AND_FINANCE",
  FINANCE = "FINANCE",
  C_LEVEL = "C_LEVEL",
  DIRECTOR_LEVEL = "DIRECTOR_LEVEL",
  MANAGER_LEVEL = "MANAGER_LEVEL",
  OTHER = "OTHER",
  VICE_PRESIDENT = "VICE_PRESIDENT",
  C_LEVEL_AND_FINANCE = "C_LEVEL_AND_FINANCE",
  C_LEVEL_AND_IT = "C_LEVEL_AND_IT",
  MEDICAL = "MEDICAL",
  DIRECTOR_LEVEL_AND_IT = "DIRECTOR_LEVEL_AND_IT",
  C_LEVEL_AND_DIRECTOR_LEVEL_AND_MANAGER_LEVEL = "C_LEVEL_AND_DIRECTOR_LEVEL_AND_MANAGER_LEVEL",
  IT = "IT",
  MANAGER_LEVEL_AND_IT = "MANAGER_LEVEL_AND_IT",
  VICE_PRESIDENT_AND_FINANCE = "VICE_PRESIDENT_AND_FINANCE",
  VICE_PRESIDENT_AND_IT = "VICE_PRESIDENT_AND_IT",
}

export enum COUNTRY_TYPES {
  SOUTH_AMERICA = "SOUTH_AMERICA",
  EUROPE = "EUROPE",
  AUSTRALIA_AND_NEW_ZEALAND = "AUSTRALIA_&_NEW_ZEALAND",
  MIDDLE_EAST = "MIDDLE_EAST",
  AFRICA = "AFRICA",
  NORTH_AMERICA = "NORTH_AMERICA",
  ASIA = "ASIA"
}